In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('MOCK_DATA.csv')

In [6]:
df.head()

,id,first_name,last_name,email,gender,ip_address
0,1,Oran,Kurt,okurt0@diigo.com,Male,22.44.205.45
1,2,Cherice,Stoggles,cstoggles1@rakuten.co.jp,Female,141.181.131.239
2,3,Phillipp,Adlard,padlard2@ca.gov,Male,224.125.201.185
3,4,Maria,Rosita,mrosita3@deviantart.com,Genderfluid,117.252.116.183
4,5,Romonda,Luckett,rluckett4@columbia.edu,Female,105.60.175.13

In [8]:
df = pd.read_csv('MOCK_DATA.csv', encoding='utf-8')

In [41]:
df = pd.read_csv('MOCK_DATA.csv')

In [9]:
df.head()

,id,first_name,last_name,email,gender,ip_address
0,1,Oran,Kurt,okurt0@diigo.com,Male,22.44.205.45
1,2,Cherice,Stoggles,cstoggles1@rakuten.co.jp,Female,141.181.131.239
2,3,Phillipp,Adlard,padlard2@ca.gov,Male,224.125.201.185
3,4,Maria,Rosita,mrosita3@deviantart.com,Genderfluid,117.252.116.183
4,5,Romonda,Luckett,rluckett4@columbia.edu,Female,105.60.175.13

In [10]:
df.tail()

,id,first_name,last_name,email,gender,ip_address
995,996,Hans,Kislingbury,hkislingburyrn@fastcompany.com,Male,96.136.110.110
996,997,Alejandro,Lehrmann,alehrmannro@google.cn,Male,0.213.157.229
997,998,Portie,Bane,pbanerp@vk.com,Male,190.228.124.114
998,999,Christye,Verrall,cverrallrq@forbes.com,Female,96.3.117.64
999,1000,Shawn,Ahrend,sahrendrr@bigcartel.com,Female,200.41.253.9

In [12]:
df.shape

(1000, 6)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1000 non-null   int64
 1   first_name  1000 non-null   object
 2   last_name   1000 non-null   object
 3   email       1000 non-null   object
 4   gender      1000 non-null   object
 5   ip_address  1000 non-null   object
dtypes: int64(1), object(5)
memory usage: 47.0+ KB

In [14]:
df.describe()

                id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

In [15]:
df['email']

0                    okurt0@diigo.com
1            cstoggles1@rakuten.co.jp
2                     padlard2@ca.gov
3             mrosita3@deviantart.com
4              rluckett4@columbia.edu
                    ...
995    hkislingburyrn@fastcompany.com
996             alehrmannro@google.cn
997                    pbanerp@vk.com
998             cverrallrq@forbes.com
999           sahrendrr@bigcartel.com
Name: email, Length: 1000, dtype: object

In [16]:
df[['last_name', 'gender','first_name', 'email']]

       last_name       gender first_name                           email
0           Kurt         Male       Oran                okurt0@diigo.com
1       Stoggles       Female    Cherice        cstoggles1@rakuten.co.jp
2         Adlard         Male   Phillipp                 padlard2@ca.gov
3         Rosita  Genderfluid      Maria         mrosita3@deviantart.com
4        Luckett       Female    Romonda          rluckett4@columbia.edu
..           ...          ...        ...                             ...
995  Kislingbury         Male       Hans  hkislingburyrn@fastcompany.com
996     Lehrmann         Male  Alejandro           alehrmannro@google.cn
997         Bane         Male     Portie                  pbanerp@vk.com
998      Verrall       Female   Christye           cverrallrq@forbes.com
999       Ahrend       Female      Shawn         sahrendrr@bigcartel.com

[1000 rows x 4 columns]

In [18]:
df.iloc[0]

id                           1
first_name                Oran
last_name                 Kurt
email         okurt0@diigo.com
gender                    Male
ip_address        22.44.205.45
Name: 0, dtype: object

In [20]:
df.loc[0]

id                           1
first_name                Oran
last_name                 Kurt
email         okurt0@diigo.com
gender                    Male
ip_address        22.44.205.45
Name: 0, dtype: object

In [21]:
df[df['id'] > 900]

,id,first_name,last_name,email,gender,ip_address
900,901,Domini,Drewet,ddrewetp0@prlog.org,Female,175.206.24.103
901,902,Ruddie,Perris,rperrisp1@google.es,Male,72.117.198.235
902,903,Stacee,Simmell,ssimmellp2@reuters.com,Male,97.167.20.158
903,904,Christophe,Plumridege,cplumridegep3@shareasale.com,Male,197.4.89.97
904,905,Lorena,Hullyer,lhullyerp4@blogtalkradio.com,Female,127.137.16.147
...,...,...,...,...,...,...
995,996,Hans,Kislingbury,hkislingburyrn@fastcompany.com,Male,96.136.110.110
996,997,Alejandro,Lehrmann,alehrmannro@google.cn,Male,0.213.157.229
997,998,Portie,Bane,pbanerp@vk.com,Male,190.228.124.114
998,999,Christye,Verrall,cverrallrq@forbes.com,Female,96.3.117.64
999,1000,Shawn,Ahrend,sahrendrr@bigcartel.com,Female,200.41.253.9

In [22]:
df['id'].max()

1000

In [23]:
df[(df['id'] > 900) & (df['gender'] == 'Female')]

,id,first_name,last_name,email,gender,ip_address
900,901,Domini,Drewet,ddrewetp0@prlog.org,Female,175.206.24.103
904,905,Lorena,Hullyer,lhullyerp4@blogtalkradio.com,Female,127.137.16.147
908,909,Lurlene,Girsch,lgirschp8@usda.gov,Female,136.236.247.35
911,912,Rosanna,Ferbrache,rferbrachepb@ehow.com,Female,71.75.21.29
914,915,Debbie,Akast,dakastpe@twitter.com,Female,250.128.136.129
915,916,Aubry,Forshaw,aforshawpf@google.it,Female,11.228.112.157
918,919,Vilhelmina,MacEveley,vmaceveleypi@seesaa.net,Female,194.230.129.174
919,920,Laurette,Minger,lmingerpj@hostgator.com,Female,229.198.44.148
921,922,Anestassia,Van der Beken,avanderbekenpl@sourceforge.net,Female,148.135.47.238
922,923,Otha,Odger,oodgerpm@princeton.edu,Female,210.170.47.215
926,927,Linea,Tennock,ltennockpq@cmu.edu,Female,170.93.27.238
927,928,Fleur,Pereira,fpereirapr@utexas.edu,Female,12.242.48.82
928,929,Terrie,Coulthart,tcoulthartps@howstuffworks.com,Female,134.122.129.118
929,930,Harriett,Sleight,hsleightpt@canalblog.com,Female,199.122.107.216
930,931,Torrie,Laver,tlaverpu@g.co,Female,100.217.132.220
931,932,Penni,Slayton,pslaytonpv@sourceforge.net,Female,25.88.84.43
932,933,Margi,Tuffs,mtuffspw@vkontakte.ru,Female,47.156.120.128
933,934,Catlee,Bradford,cbradfordpx@sitemeter.com,Female,223.169.166.148
935,936,Brenda,Datte,bdattepz@nba.com,Female,37.94.140.197
940,941,Mommy,Meech,mmeechq4@cyberchimps.com,Female,41.153.127.234
941,942,Hyacinthie,Aleksandrev,haleksandrevq5@arstechnica.com,Female,215.171.31.235
942,943,Katinka,Beardow,kbeardowq6@dmoz.org,Female,132.21.243.54
945,946,Rhea,Ismail,rismailq9@marriott.com,Female,254.152.222.7
946,947,Joni,Fetherston,jfetherstonqa@netvibes.com,Female,122.115.152.59
947,948,Lonna,Blakesley,lblakesleyqb@bloglines.com,Female,101.102.139.78
948,949,Luise,Masseo,lmasseoqc@jalbum.net,Female,202.243.141.65
949,950,Stephie,Toope,stoopeqd@adobe.com,Female,6.151.52.27
952,953,Athene,Delamere,adelamereqg@ft.com,Female,39.98.35.84
953,954,Gretta,Redmore,gredmoreqh@arstechnica.com,Female,89.71.31.120
955,956,Cami,Posselt,cposseltqj@zimbio.com,Female,40.161.72.65
959,960,Zorah,Attwool,zattwoolqn@washington.edu,Female,140.177.17.159
963,964,Brena,Nattrass,bnattrassqr@squidoo.com,Female,26.220.8.242
968,969,Nadia,Klousner,nklousnerqw@wp.com,Female,240.68.198.241
969,970,Barbra,Charity,bcharityqx@purevolume.com,Female,254.88.106.100
973,974,Jacinda,Ajam,jajamr1@is.gd,Female,95.17.181.15
978,979,Priscilla,Weed,pweedr6@studiopress.com,Female,178.245.118.95
980,981,Nannie,Slater,nslaterr8@themeforest.net,Female,220.30.134.225
981,982,Prudence,Kadwallider,pkadwalliderr9@columbia.edu,Female,64.173.165.181
983,984,Karola,Rosenqvist,krosenqvistrb@army.mil,Female,125.107.232.232
984,985,Lexis,Strattan,lstrattanrc@wikipedia.org,Female,152.181.46.157
989,990,Guglielma,Buckoke,gbuckokerh@gizmodo.com,Female,244.30.249.59
994,995,Fina,Shirtliff,fshirtliffrm@altervista.org,Female,178.152.60.148
998,999,Christye,Verrall,cverrallrq@forbes.com,Female,96.3.117.64
999,1000,Shawn,Ahrend,sahrendrr@bigcartel.com,Female,200.41.253.9

In [25]:
df['newcol'] = df['id'] + 2

In [26]:
df['id'] = df['id'] * 2

In [27]:
df.drop('first_name',axis=1, inplace=True)

In [28]:
df.drop(0, axis=0, inplace=True)

In [29]:
df = pd.read_csv('MOCK_DATA.csv')

In [30]:
df.head()

,id,first_name,last_name,email,gender,ip_address
0,1,Oran,Kurt,okurt0@diigo.com,Male,22.44.205.45
1,2,Cherice,Stoggles,cstoggles1@rakuten.co.jp,Female,141.181.131.239
2,3,Phillipp,Adlard,padlard2@ca.gov,Male,224.125.201.185
3,4,Maria,Rosita,mrosita3@deviantart.com,Genderfluid,117.252.116.183
4,5,Romonda,Luckett,rluckett4@columbia.edu,Female,105.60.175.13

In [31]:
df.sort_values('gender', ascending=True)

,id,first_name,last_name,email,gender,ip_address
923,924,Bertina,Galvan,bgalvanpn@yolasite.com,Agender,98.174.103.246
130,131,Kerby,Pessler,kpessler3m@businesswire.com,Agender,201.124.20.237
157,158,Sigismondo,Rookesby,srookesby4d@squarespace.com,Agender,26.13.231.164
638,639,Lonni,Neenan,lneenanhq@businessinsider.com,Agender,125.71.6.230
172,173,Dorrie,Pagram,dpagram4s@tmall.com,Agender,141.175.135.197
...,...,...,...,...,...,...
503,504,Nadia,Ceeley,nceeleydz@pagesperso-orange.fr,Polygender,102.105.56.108
98,99,Kasey,Rickhuss,krickhuss2q@businessweek.com,Polygender,228.198.195.48
639,640,Kristin,Ruston,krustonhr@histats.com,Polygender,231.58.228.251
917,918,Aldous,Golston,agolstonph@webmd.com,Polygender,139.250.118.18
111,112,Terrye,Hare,thare33@mit.edu,Polygender,11.58.50.154

In [32]:
df.isnull().sum()

id            0
first_name    0
last_name     0
email         0
gender        0
ip_address    0
dtype: int64

In [34]:
df.dropna(inplace=True)

In [35]:
df.fillna(0,inplace=True)

In [36]:
df.to_csv('output.csv', index=False)